services:
  - type: web
    name: electricity-manager
    env: python
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:create_app\(\) -b 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: "8018"
